services:
  - type: web
    name: eaukey-backend
    env: python
    pythonVersion: 3.13.4
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
